// AUTO-GENERATED by scripts/sync-article-registry.mjs  -  do not edit manually
import type { BlogArticleMeta } from "@/lib/content/collections/blog"
import type { ResourceArticleMeta } from "@/lib/content/collections/resources"
import type { VisaGuideArticleMeta } from "@/lib/content/collections/visa-guides"
import type { ContentArticleModule } from "@/lib/content/types"

export const generatedArticleEntries = {
  "blog/best-visa-for-living-in-thailand": {
    collection: "blog",
    slug: "best-visa-for-living-in-thailand",
    loadMeta: () =>
      import("@/content/articles/blog/best-visa-for-living-in-thailand/meta").then(
        (m) => m.meta,
      ),
    loadModule: async () => {
      const [{ default: Content }, { meta }] = await Promise.all([
        import("@/content/articles/blog/best-visa-for-living-in-thailand/content.mdx"),
        import("@/content/articles/blog/best-visa-for-living-in-thailand/meta"),
      ])
      return { default: Content, meta }
    },
  },
  "blog/business-visa-vs-work-permit-thailand": {
    collection: "blog",
    slug: "business-visa-vs-work-permit-thailand",
    loadMeta: () =>
      import("@/content/articles/blog/business-visa-vs-work-permit-thailand/meta").then(
        (m) => m.meta,
      ),
    loadModule: async () => {
      const [{ default: Content }, { meta }] = await Promise.all([
        import("@/content/articles/blog/business-visa-vs-work-permit-thailand/content.mdx"),
        import("@/content/articles/blog/business-visa-vs-work-permit-thailand/meta"),
      ])
      return { default: Content, meta }
    },
  },
} as const

export type GeneratedArticleRegistryKey = keyof typeof generatedArticleEntries
