// AUTO-GENERATED by scripts/sync-article-registry.mjs  -  do not edit manually
import type { BlogArticleMeta } from "@/lib/content/collections/blog"
import type { GuideArticleMeta } from "@/lib/content/collections/guides"
import type { ResourceArticleMeta } from "@/lib/content/collections/resources"
import type { VisaGuideArticleMeta } from "@/lib/content/collections/visa-guides"
import type { ContentArticleModule } from "@/lib/content/types"

export const generatedArticleEntries = {
  "guides/business-visa-vs-work-permit-thailand": {
    collection: "guides",
    slug: "business-visa-vs-work-permit-thailand",
    loadMeta: () =>
      import("@/content/articles/guides/business-visa-vs-work-permit-thailand/meta").then(
        (m) => m.meta,
      ),
    loadModule: async () => {
      const [{ default: Content }, { meta }] = await Promise.all([
        import("@/content/articles/guides/business-visa-vs-work-permit-thailand/content.mdx"),
        import("@/content/articles/guides/business-visa-vs-work-permit-thailand/meta"),
      ])
      return { default: Content, meta }
    },
  },
  "guides/how-to-get-thailand-retirement-visa": {
    collection: "guides",
    slug: "how-to-get-thailand-retirement-visa",
    loadMeta: () =>
      import("@/content/articles/guides/how-to-get-thailand-retirement-visa/meta").then(
        (m) => m.meta,
      ),
    loadModule: async () => {
      const [{ default: Content }, { meta }] = await Promise.all([
        import("@/content/articles/guides/how-to-get-thailand-retirement-visa/content.mdx"),
        import("@/content/articles/guides/how-to-get-thailand-retirement-visa/meta"),
      ])
      return { default: Content, meta }
    },
  },
} as const

export type GeneratedArticleRegistryKey = keyof typeof generatedArticleEntries
