import type { VisaSlug } from "@/lib/visas/types"

/** Stable section and heading ids per visa page  -  for landmarks and SEO */
export function getVisaSectionIds(slug: VisaSlug) {
  return {
    hero: `${slug}-hero`,
    heroHeading: `${slug}-hero-heading`,
    lastUpdated: `${slug}-last-updated`,
    definition: `${slug}-definition`,
    definitionHeading: `${slug}-definition-heading`,
    keyFacts: `${slug}-key-facts`,
    keyFactsHeading: `${slug}-key-facts-heading`,
    gettingStarted: `${slug}-getting-started`,
    gettingStartedHeading: `${slug}-getting-started-heading`,
    bestFor: `${slug}-best-for`,
    bestForHeading: `${slug}-best-for-heading`,
    overview: `${slug}-overview`,
    overviewHeading: `${slug}-overview-heading`,
    officialSources: `${slug}-official-sources`,
    officialSourcesHeading: `${slug}-official-sources-heading`,
    entityGlossary: `${slug}-entity-glossary`,
    entityGlossaryHeading: `${slug}-entity-glossary-heading`,
    comparison: `${slug}-comparison`,
    comparisonHeading: `${slug}-comparison-heading`,
    requirements: `${slug}-requirements`,
    requirementsHeading: `${slug}-requirements-heading`,
    checklist: `${slug}-checklist`,
    checklistHeading: `${slug}-checklist-heading`,
    feesAndTimelines: `${slug}-fees-timelines`,
    feesAndTimelinesHeading: `${slug}-fees-timelines-heading`,
    governmentProcess: `${slug}-government-process`,
    governmentProcessHeading: `${slug}-government-process-heading`,
    pitfalls: `${slug}-pitfalls`,
    pitfallsHeading: `${slug}-pitfalls-heading`,
    practiceInsights: `${slug}-practice-insights`,
    practiceInsightsHeading: `${slug}-practice-insights-heading`,
    embassyVarianceTable: `${slug}-embassy-variance`,
    embassyVarianceTableHeading: `${slug}-embassy-variance-heading`,
    compliance: `${slug}-compliance`,
    complianceHeading: `${slug}-compliance-heading`,
    legalBoundaries: `${slug}-legal-boundaries`,
    legalBoundariesHeading: `${slug}-legal-boundaries-heading`,
    decisionGuides: `${slug}-decision-guides`,
    decisionGuidesHeading: `${slug}-decision-guides-heading`,
    process: `${slug}-process`,
    processHeading: `${slug}-process-heading`,
    faq: `${slug}-faq`,
    faqHeading: `${slug}-faq-heading`,
    eeat: `${slug}-eeat`,
    eeatHeading: `${slug}-eeat-heading`,
    relatedResources: `${slug}-related-resources`,
    relatedResourcesHeading: `${slug}-related-resources-heading`,
    relatedVisas: `${slug}-related-visas`,
    relatedVisasHeading: `${slug}-related-visas-heading`,
    finalCta: `${slug}-contact`,
    finalCtaHeading: `${slug}-contact-heading`,
  } as const
}

export type VisaSectionIds = ReturnType<typeof getVisaSectionIds>
